remove unnecessary extra semicolon so it can build with pedantic GCC flag
./cpuaff/include/cpuaff/impl/linux_impl/sysfs_reader.hpp:274:2: error: extra ‘;’ [-Werror=pedantic]